affinity: {}
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

nameOverride: ""
fullnameOverride: ""

groupName: de.su541.acme
image:
  repository: "ghcr.io/su541/cert-manager-desec-webhook"
  tag: latest
  pullPolicy: IfNotPresent

secretName:
  - desec-io-token

service:
  port: 443
  type: ClusterIP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []
